# NumPy Indexing and Selection

In [18]:
import numpy as np

arr = np.arange(10,50)

#Indexing simple array

arr[8]

arr[0:5] #slicing 0 to 5

arr[5:] #slicing 5 to end 

arr[0:5] = 100 #set elements 0 to 5 equal to 100

arr_copy = arr.copy() #creates a new copy of the array


#Indexing matrix

arr2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

arr2d[0][0] #grabs row 0 col 0

arr2d[0,0] #shorthand

arr2d[:,1] #grabs all data in col 1

arr2d[1,:] #grabs all data in row 1

array([20, 25, 30])

In [22]:
#Conditional Indexing

arr = np.arange(1,11)

bool_arr = arr > 5 #create an array of bool where element > 5

arr[bool_arr] #create an array where elements meet bool criteria

arr[arr>5] #shorthand conditional selection



array([ 6,  7,  8,  9, 10])

In [32]:
#Practice: get rows 4 through 7

arr2d = np.arange(50).reshape(5,10)

arr2d[:,4:8]



array([[ 4,  5,  6,  7],
       [14, 15, 16, 17],
       [24, 25, 26, 27],
       [34, 35, 36, 37],
       [44, 45, 46, 47]])