# NumPy Arrays

In [2]:
import numpy as np

#Convert list to np.array
my_list = [1,2,3]

arr = np.array(my_list)

print(arr)

[1 2 3]


In [5]:
#Casting list to 2D array
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#Creating an np arrays

np.arange(0,10)

np.zeros(3) #creates array of zeros

np.zeros((2,3)) #2 by 3 array of zeros

np.ones((2,3)) #... of ones

np.linspace(0,5,10) #one dim vector of 10 evenly spaced points from 0 to 5

np.eye(4) #4x4 matrix with diagonal of 1s 

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [18]:
#Random Sampling

np.random.rand(5,5) #5x5 array of uniformly distributed random nums

np.random.randn(5,5) #5x5 array of normally distributed random nums, center=0

np.random.randint(1,101,10) #10 random ints from (1,101]


array([ 8, 96, 38, 37, 50, 15, 93,  3, 70, 70])

In [31]:
#Array methods

arr = np.arange(25)

arr.shape #get the shape of the array

arr.reshape(5,5) #change the dim of array to 5x5 matrix (rows x rols == elements in array)

ranarray = np.random.randint(0,50,10)

ranarray.max() 

ranarray.min()

ranarray.argmax() #index of the max value

ranarray.argmin() #index of the min value

ranarray.dtype #get the type of the data



dtype('int64')