# Review

In [12]:
#For Loops List Comprehension

"""
Write a python code that creates a new list taking the power of each value by 2
"""
numls = [1,2,3,4]

ans = [num**2 for num in numls]

numlsAlt = [1,2,3,4]

ansAlt = [numlsAlt[i]**2 for i in range(len(numlsAlt))]

print(ans)
print(ansAlt)


[1, 4, 9, 16]
[1, 4, 9, 16]


In [20]:
#Lambda - shorthand way to write a function
#lambda inputVar:returnOperation


"""
Write a function that multiplies by 3
"""

def multiply3_old(num):
    ans = num*3
    return ans
    
print(multiply3_old(7))

#Now using lambda
multiply3 = lambda num: num*3

print(multiply3(7))


21
21


In [26]:
#Map Function - preform func on each element of a list

square2 = lambda num: num**2

print(square2(7))

seq = [123,42,54,23,34,68,9,8,32,12,23,1]

ans = list(map(square2, seq))

print(ans)




49
[15129, 1764, 2916, 529, 1156, 4624, 81, 64, 1024, 144, 529, 1]


In [28]:
#Filter - returns the elements that meets the criteria of a function

getEven = lambda num: num % 2 == 0

seq = [1,2,3,4,5,6,7,8,9,10]

ans = list(filter(getEven,seq))

print(ans)

[2, 4, 6, 8, 10]


In [51]:
#Numpy array Indexing
import numpy as np

my_list = [1,2,3,4]

arr = np.array(my_list)

my_matrix = [[1,2,3],
             [4,5,6],
             [7,8,9]]

np_matrix = np.array(my_matrix)

np_matrix[0:2,1:3]

np_matrix[:,0]

#Conditional Indexing

numls = np.arange(1,11)

greater5 = numls > 5 #create array of bool where element > 5

numls[greater5] #create an array where elements meet bool criteria

numls[numls > 5] #shorthand


[1 2 3 4]
[[2 3]
 [5 6]]
[1 4 7]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [72]:
#npArrays Methods
import numpy as np

#Creating npArrays
np.arange(0,10) #creates array 1 to 9

np.zeros(3) #creates array of zeros

np.zeros((2,3)) #2 by 3 matrix of zeros

np.ones((2,3)) #2 by 3 matrix of ones

np.linspace(0,5,10) #one dim vector of 10 evenly spaced points from 0 to 5

np.eye(4) #4x4 matrix with diagonal of 1s

#npArray Operations
numls = np.arange(50)

numls.shape #get the shape of the array

numls_matrix = numls.reshape(5,10) #change the dim of array to 5x5 matrix (rows x rols == elements in array)

numls_matrix.max()

numls_matrix.min()

numls_matrix.argmax() #index of the max value

numls_matrix.argmin() #index of the min value

numls_matrix.dtype #get the data type

matrix_copy = numls_matrix.copy() #creates a new copy of the array

"""
Practice: create a matrix 5x5 of values 1 to 50 and get the columns 3 to end.
"""

matrix5x5 = np.arange(1,26).reshape(5,5)

print(matrix5x5)

matrix5x5[:,2:]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [77]:
#npArrays Randomizing
import numpy as np

np.random.randint(0,50,6) #6 random nums between 0 and 50

np.random.rand(5,5) #5x5 matrix of uniformly distributed random nums

np.random.randn(5,5) #5x5 matrix of normally distributed random nums, center=0



array([[ -9.36796162e-01,   1.51464518e-01,  -3.31744986e-01,
          3.69846532e-01,   2.76871949e-01],
       [  1.11939916e+00,   8.35123935e-01,  -9.34346623e-04,
         -1.16949455e+00,   1.81789319e-01],
       [  3.50974883e-01,  -1.80042787e-01,   2.96331898e-01,
          2.12748457e+00,  -1.56802592e+00],
       [  2.72116522e-01,  -5.08555223e-01,  -5.16297253e-01,
          4.30928282e-01,  -1.10001119e+00],
       [ -2.67972706e-01,   6.67834945e-01,  -4.79310125e-01,
         -1.73018414e+00,   2.89368006e-01]])